### ISSUE TITLE
Set up access permissions for Matt

### ISSUE THREAD

**Issue by livlab** [thecarebot/carebot#11]
- VPN?
- auth IP?

**Comment by livlab** [comment]
- [ ] Facebook Analytics
- [x] Google Analytics
- [ ] Twitter Analytics
- [x] NPR API
- [x] AWS

**Comment by hampelm** [comment]
Eads is adding me to the graeae server.

**Comment by brianboyer** [comment]
closing. will make a new ticket for facebook stuff when we do facebook stuff
