### ISSUE TITLE
How to message metrics for stories with 2+ graphics

### ISSUE THREAD

**Issue by livlab** [thecarebot/carebot#114]
One small ux complication:
Some stories have multiple graphics
(each with its own slug)
The code will report on each of them
the question is the wording

**Comment by livlab** [comment]
![image](https://cloud.githubusercontent.com/assets/1936365/13327366/84b6fbe4-dbb7-11e5-8550-f58131b5236b.png)

**Comment by hampelm** [comment]
![pasted image at 2016_02_29 02_24 pm](https://cloud.githubusercontent.com/assets/86435/13406404/4e5befc2-def1-11e5-9fd5-e681bb85bda0.png)

Per slack discussion, I'll use the "fields" formatting: https://api.slack.com/docs/attachments#message_formatting

**Comment by hampelm** [comment]
First draft has been deployed!
