### ISSUE TITLE
Track stories in other spreadsheets

### ISSUE THREAD

**Issue by livlab** [thecarebot/carebot#128]
From Aly: "weird carebot edge case: sometimes there will be graphics i don’t want to share with stations, but i still want to track them. i stash those in a different tab of the spreadsheet (“archive”). (lately, this has been b/c these graphics contain ap data that we can’t redistribute. i started the tab, though, b/c i was logging old graphics and didn’t want to send out extraneous notifications to stations on our email list.)"

**Comment by brianboyer** [comment]
this works with our new config setup
