### ISSUE TITLE
Histograms for linger time

### ISSUE THREAD

**Issue by hampelm** [thecarebot/carebot#130]
For a prototype, we can use the ancient google charts API

https://developers.google.com/chart/image/docs/chart_playground

https://developers.google.com/chart/image/docs/chart_params

**Comment by hampelm** [comment]
```
cht=bvg
chs=250x150
chd=t:10,20,50,20,10
chxt=x,x,y
chco=e13452
chxs=0,e13452,12,0,lt
     2,N*100*k,e13452,10,1,lt
chof=png
chma=30,10,15,20
chxl=1:|Seconds
     0:|10|20|30|40|50
chxp=1,50
```

http://chart.googleapis.com/chart?cht=bvg&chs=250x150&chd=t:10,20,50,20,10&chxt=x,x,y&chco=e13452&chxs=0,e13452,12,0,lt|2,N*100*k,e13452,10,1,lt&chof=png&chma=30,10,15,20&chxl=1:|Seconds|0:|10|20|30|40|50&chxp=1,50

**Comment by livlab** [comment]
Iterated a few times; good feedback from Aly, Tyler and Katie. Kind of depends on how much we can tweak, but this would be a good place to get to: 
![image](https://cloud.githubusercontent.com/assets/1936365/13501629/723869d4-e135-11e5-9e27-fc063a740b9a.png)

**Comment by hampelm** [comment]
First draft implemented!
