### ISSUE TITLE
Show how many visitors saw the graphic at all 

### ISSUE THREAD

**Issue by hampelm** [thecarebot/carebot#131]
Aly suggests: 

> After 2 days, ​_50%_​ of visitors to ​_A History Of Super Tuesday_​ saw the graphic. Those who have seen the graphic have spent, on average, ​_47 seconds_​ studying the graphic.

**Comment by brianboyer** [comment]
something like this is a good idea we think

**Comment by hampelm** [comment]
I'm gonna take Tyler's plugin and tidy it up for inclusion

**Comment by hampelm** [comment]
It's over here: https://github.com/thecarebot/carebot/tree/unsuck

**Comment by hampelm** [comment]
Done in #338
