### ISSUE TITLE
Decide if we should attend the bot-focused Code Convening, and what we should accomplish there

### ISSUE THREAD

**Issue by hampelm** [thecarebot/carebot#146]
https://docs.google.com/forms/d/1EoJ_imloJke4aIkt4zYzNBGbCagHO9q7W9T2yM_rIFc/viewform

**Comment by livlab** [comment]
- [x] agree we want to do it
- [x] talk to Ryan about partner with local newsroom idea
- [x] fill out the form and sent to

**Comment by livlab** [comment]
Texas Tribune likely candidate. 
We'll hear back from Ryan by Friday the latest.
