### ISSUE TITLE
Get Matt API Access to Google Analytics

### ISSUE THREAD

**Issue by livlab** [thecarebot/carebot#15]

**Comment by livlab** [comment]
@hampelm you should have received an invitation by email just now from Dan F. Please let me know:
-  [x] GA client access works for NPR and Visuals properties
-  [x] GA API access works for NPR and Visuals properties
  so we can close this issue.

**Comment by hampelm** [comment]
I can access analytics via the web. Checking on API access.

**Comment by hampelm** [comment]
API access good to go!
