### ISSUE TITLE
Use full headlines?

### ISSUE THREAD

**Issue by hampelm** [thecarebot/carebot#171]
From Aly:

> one other carebot thought — i’m noticing a mix of headline treatments now? sometimes truncated, sometimes not. i find having the full headline is helpful to jog my memory about what the graphic was.

cc @livlab

**Comment by livlab** [comment]
had an exchange with Aly the other day, I presumed full headlines would make the messages convoluted and hard to scan, but I was wrong! they find full headlines more helpful than not, so let's just go with full headlines everywhere.
