### ISSUE TITLE
Support tracking stories from multiple locations

### ISSUE THREAD

**Issue by hampelm** [thecarebot/carebot#178]
We need to support tracking stories from multiple sources. Right now, that's google spreadsheets and RSS. We also need to post updates from those stories to multiple channels. We want to avoid a full-fledged admin system to keep things simple. 

The plan: 
Add a yml file that specifies source type, source details (eg URL), team name, and channel. As part of the cron job, the app will: 
- Read that file
- Dispatch each specified scraper
- Save the stories to the same DB we have been using, but add a column to store story team
- Post updates to the team's channel

We need to:
- Add the YML dispatcher
- Add an RSS scraper
- Dispatch updates to the the channel of the team, rather than to the global config channel

Deploy: There should only be one yml file (not a `staging.yml` and `production.yml`). This will reduce breakage. It does mean that the staging slack will need to have the same channels as the live slack.

**Comment by livlab** [comment]
\m/
