### ISSUE TITLE
broken link on headline in list of stories

### ISSUE THREAD

**Issue by livlab** [thecarebot/carebot#186]
![image](https://cloud.githubusercontent.com/assets/1936365/14022161/059160b6-f1b5-11e5-9e65-4c2717123b88.png)

**Comment by hampelm** [comment]
I think it's a problem handling single quotes; happens in other contexts: 

![screen shot 2016-03-24 at 11 47 57 am](https://cloud.githubusercontent.com/assets/86435/14023151/6bae1bce-f1b9-11e5-9d01-7857172d089a.png)

**Comment by hampelm** [comment]
I figured it out Friday! There was a newline. Opened issue #204 to fix.
