### ISSUE TITLE
Look up metrics desired by Graphics team

### ISSUE THREAD

**Issue by livlab** [thecarebot/carebot#19]
capture what other metrics would be relevant to this team and see if we can include in phase 1

**Comment by livlab** [comment]
i.e.: quotes from comments mentioning the graphic

**Comment by livlab** [comment]
@hampelm, here's a summary of insights from interviewing Aly last year:
- having to manually add a story to start tracking is inconvenient (stopped using Carebot because she'd forget to do this)
- metric: how many comments the story got 
- metric: how many comments were moderated, as a sense of how heated/ridiculous the conversation got (short of sentiment analysis)
- carebot: would also like it to be more transparent about how old/recent the data is; know traffic numbers are several hours behind, but i don't have a good sense of how behind
- graphics projects separate from other types of stories so comparisons are apples to apples.
- metrics: number of actual graphics impressions (graphics appearing in the user's viewport)
- metrics: pick-up by member stations, reach (distribution) 
- success/failure for a graphics story: pitiful traffic and/or low engagement :) - compared to how other stories did that day, or other graphics of that type (will often mentally judge vs. how other stories in the top 20 for a given day did)
- success/failure for a graphics story: personal satisfaction - was it interesting to work on — interesting subject, a new technical skill, an artistic treatment — or were the folks involved particularly happy with it
- metrics: graphics mentions in comments; do people cite the graphic as having helped them understand something

**Comment by hampelm** [comment]
Thanks, this is super helpful to know. 

Clearly stating the data age is feedback is something we should def. pay attention to. 

Maybe rev 2 or 3 can include some sort of comment measure.
