### ISSUE TITLE
Explore metrics: unsuck pageviews

### ISSUE THREAD

**Issue by livlab** [thecarebot/carebot#197]
It is unreasonable for people to stop carrying about reach in terms of pageviews. How can we unsuck it? 

How can we offer what they want but give them what they need?  Potential here for making pageviews more meaningful or at least comparable by introducing comparison of like stories rather than overall ranking of all stories
- requires story classification.

**Comment by livlab** [comment]
https://github.com/thecarebot/thecarebot.github.io/commit/caaecf52788e4a63c8e0f062a67a286de9990379

**Comment by livlab** [comment]
Not gonna finish today. Will collect all explorations in a blog post (above).

**Comment by hampelm** [comment]
Simple pageviews inquiry added with #338
