### ISSUE TITLE
Design the notification UI

### ISSUE THREAD

**Issue by livlab** [thecarebot/carebot#22]
See scope #9

**Comment by livlab** [comment]
![image](https://cloud.githubusercontent.com/assets/1936365/12854920/69b30bc4-cc0a-11e5-955c-0f0903de5f4c.png)
- I believe a bot gets a 'bot' tag added by default (will double check the API docs)
- Truncate the project_title by 6 words and add an ellipsis (do not display full headline/title, it's always too long and here it is just a reminder for the team of what story this is)
- Link the project_title to the public url where it is published.
- Use default behavior and color for links.
- Make the value and unit for measure for the metric shown **bold**.

**Comment by livlab** [comment]
Also:
- Because these projects are graphics stories, they get categorized as such and only posted to visuals-graphics channel. (implication: need to have a method to route to the right channel based on how the project is classified in the taxonomy - for phase one it won't be necessary)

**Comment by livlab** [comment]
I'm wondering if for the first message when Carebot starts tracking, can be both more simple/straightforward AND more useful — some exploration:

![image](https://cloud.githubusercontent.com/assets/1936365/12856330/5d25f364-cc12-11e5-8a0f-9cb711e6d703.png)

**Comment by livlab** [comment]
Non-map example (more common use):
![image](https://cloud.githubusercontent.com/assets/1936365/12856522/5b74afb4-cc13-11e5-9538-b8ea05fc2b08.png)

**Comment by livlab** [comment]
if including image, it probably needs an outline:

![image](https://cloud.githubusercontent.com/assets/1936365/12856622/cf495b9c-cc13-11e5-8d17-9f8e4ce66689.png)

**Comment by livlab** [comment]
- [x] Checked the [Slack API docs](https://api.slack.com/bot-users) and confirmed that bot users get a [BOT] tag by default.

**Comment by livlab** [comment]
- [x] request feedback
- [x] iterate visuals as needed

**Comment by hampelm** [comment]
Looks good all around! 

I like including an image with the article to add context / remind people what it's tracking. If articles aren't already automatically posted, it might have the nice side effect of letting people other than the author know what's new. 

On the other hand, if the message is only intended to confirm to the author that the piece is tracked, then no image might be more compact & subtle in the stream. We could then include the image with a later update, when there's more interesting information to share. 

I think Slack may automatically add the frame around images. We'll find out!

**Comment by livlab** [comment]
Good points, thank you!

**Comment by livlab** [comment]
Capturing all UI documentation at https://github.com/thecarebot/carebot/wiki/Carebot-UI going forward.
