### ISSUE TITLE
Explain adding slackbot

### ISSUE THREAD

**Issue by hampelm** [thecarebot/carebot#243]
- Note that you need an open integration
- Explain how to add an integration 
- Custom integrations: 
  -- yourteam.slack.com/apps/manage/custom-integrations
  -- go to "bots" 
  -- Click "add configuration" 
  -- Fill in with "@carebot" 
  -- Click "Add integration
  -- That will give you an API token 
  -- NB: we should supply an icon for this screen
- You might want to create a private channel for testing the bot
- You'll have to invite the bot to the channels you want

**Comment by livlab** [comment]
note to people that once you make a channel private it can't be made public later.

**Comment by hampelm** [comment]
@livlab Can you drop the Carebot png icon in this issue?

**Comment by livlab** [comment]
https://github.com/thecarebot/thecarebot.github.io/blob/master/images/Carebot.png
