### ISSUE TITLE
Move team from Hipchat to Slack

### ISSUE THREAD

**Issue by livlab** [thecarebot/carebot#27]
simple :)

**Comment by livlab** [comment]
- [x] Set up Matt and Livia with a carebot channel first

**Comment by livlab** [comment]
@brianboyer Do you think you'll be able to make this happen by the 11th? I'm wondering how much time people will have to get used to it before we introduce a new thing (Carebot) - a week seems like a good lead time if possible (phase one ends on the 18th).

**Comment by brianboyer** [comment]
I'm gonna try to make it happen this week. Which chat room do you think is
best? Should we use the room for the whole team, or just the graphics room
for this test?

**Comment by livlab** [comment]
When we last talked, I understood that the various visuals hipchat rooms, like graphics, would have a new equivalent in Slack, so for our first rev visuals-graphics would be the room to test Carebot in.

**Comment by livlab** [comment]
This is blocked until the NPR slack account upgrades.

We'll continue doing development in separate Carebot account, testing with users in NPR account.

**Comment by brianboyer** [comment]
nevermind. this will happen when it happens

**Comment by brianboyer** [comment]
REOPENING SO I CAN CLOSE IT

**Comment by brianboyer** [comment]
DONE

**Comment by livlab** [comment]
🏆
