### ISSUE TITLE
RSS feed timezone

### ISSUE THREAD

**Issue by livlab** [thecarebot/carebot#291]
Published a story at 11am, Carebot started tracking right away, but timestamp said 3pm.

Matthew Hampel [12:56 PM] 
Looks like an issue with the feed — maybe timezone related?
https://thecarebot.github.io/feed.xml
Could you see if there’s a way to make the feed show the same time (maybe it has to be set to a timezone manually in the feed template??)

Look at how the rss is created on jekyll and if we can set/config/adjust

**Comment by livlab** [comment]
http://jekyll.tips/tutorials/rss-feed/

**Comment by livlab** [comment]
There is no good documentation on this but I think Github pages creates a default xml for you if you don't have one (if you didn't set up an xml template for jekyll to use). I realize this because I was surprised to learn we had a feed already when @hampelm first needed it. Now this makes sense.

So, I think whatever the default template Github Pages is using has a mismatch in timezone. I'll try to fix this by creating our own template and setting times to match the timezone which is already established in each blog post yaml front matter.

**Comment by livlab** [comment]
the offending line:
`<pubDate>{{ post.date | date: "%a, %d %b %Y %H:%M:%S %z" }}</pubDate>`

**Comment by livlab** [comment]
added atom feed template to root

https://github.com/thecarebot/thecarebot.github.io/commit/d58e11870dfc632316a2d162f224d5e0ea5b4049

**Comment by livlab** [comment]
Not sure how to test this -- I think just wait until the next blog post to force a feed update and we'll see the result.

**Comment by hampelm** [comment]
Could try adjusting an old post's text or headline?

**Comment by livlab** [comment]
Yeah, I just did it. 

Sadly, it didn't work. Trying to figure out what should be configured.

**Comment by hampelm** [comment]
@livlab Did you end up getting the timezones from the blog happy? I seem to remember yes? In any case, I believe this would be a ticket for the blog so inclined to close it for now.
