### ISSUE TITLE
Decide what tools we'll use to manage the work

### ISSUE THREAD

**Issue by livlab** [thecarebot/carebot#3]
- Github
- Google Docs
- Maybe Trello if Matt is into Kanban? Let's discuss.

**Comment by hampelm** [comment]
Have you used waffle.io? I like it a lot -- it's github issues in the back, and trello-like cards in the front! Here's an example: https://waffle.io/hampelm/brickbeam

**Comment by livlab** [comment]
Haven't tried it but looks good!

**Comment by livlab** [comment]
- Slack or hipchat?

**Comment by livlab** [comment]
- Github
- Waffle.io
- Google Docs
- Slack

**Comment by livlab** [comment]
Matt loves screenshots on Github!

**Comment by livlab** [comment]
Capture gifs - http://www.cockos.com/licecap/ (great for little interactions!)

**Comment by livlab** [comment]
I might try Macaw and Invision for wireframes/prototypes

**Comment by livlab** [comment]
- We'll use Bootstrap for FE framework

**Comment by livlab** [comment]
- Adopt Travis CI
