### ISSUE TITLE
Associate metrics with teams

### ISSUE THREAD

**Issue by hampelm** [thecarebot/carebot#308]

**Comment by hampelm** [comment]
@brianboyer I've got a dumb conundrum here. I think there's a simple solution-- thinking out loud. 

Right now we register plugins in one place. Plugins can listen for inquiries (eg `@carebot hello`)  Also, every 15 minutes, for every story in the database, we call every plugin's `get_update_message` method (if it has one).

If we want to associate teams with stats, we'd need to register plugins in the `config.yml`. We'd still need to register them somewhere centrally to listen for questions (since those aren't associated with teams). 

One solution would be to auto-discover plugins for listening for inquiries. I think in that case we'd need to give every plugin the same class name to make dynamic importing possible? eg we'd go from

`from plugins.npr.help import NPRHelp`

to 

`from plugins.npr.help import CarebotPlugin`

(and we could auto-import like so: http://stackoverflow.com/a/1057534/117014) 

Having all plugins have the same class name is a little unwieldy but I think would work...

**Comment by hampelm** [comment]
Someone else doing it in a similar way: https://michaelheap.com/python-dynamically-load-all-modules-in-a-folder/

Does this feel too crazy?

**Comment by brianboyer** [comment]
I'm curious what @eads thinks. One solution we discussed was doing it like
adding an app to Django, right? Where instead of directly importing the
class, you do an import using a string-formatted class name, right?

**Comment by hampelm** [comment]
That's the direction I'm investigating. The issue is that you'd need to put the string in two places (associated with teams in `config.yml`, and in a more generic location for plugins that aren't associated with teams, like "help" or "hello" or "how is slug x-y-z doing?". I'm hoping for a more elegant solution where they only need to be included once -- like autodiscovery.
