### ISSUE TITLE
Sketch out the Carebot architecture

### ISSUE THREAD

**Issue by livlab** [thecarebot/carebot#31]
(as few external dependencies as we can :) )

**Comment by hampelm** [comment]
Current strategy:
- Slackbot using the python API wrapper
- Small python library for pulling the analytics we need that talks to the slackbot 
- Python Script for periodically pulling and saving the analytics we need
- SQLite database for simplicity; may use the graeae Postgres database later if needed; will use the [peewee ORM](http://docs.peewee-orm.com/en/latest/)
- Deployed to an EC2 small
