### ISSUE TITLE
Create DB to store stories

### ISSUE THREAD

**Issue by livlab** [thecarebot/carebot#40]
- story name
- story publish date
- Seamus ID
- Date added to DB/tracker
- story URL

**Comment by hampelm** [comment]
Should probably pull from the existing doc: [removed link to internal doc]

**Comment by livlab** [comment]
I'm taking this out of phase one as we are not storing things for now.

**Comment by livlab** [comment]
@brianboyer shared an idea: Carebot should read RSS
- it's a standard format
- there are (likely) good rss parsers that have figured out issues like "have we seen this story already"
- easier for future people who want to try Carebot.

To consider when architecting storage and such.

**Comment by hampelm** [comment]
We're using a small sqlite db that feeds from the story spreadsheet.
