### ISSUE TITLE
Solve Slack account integration limits

### ISSUE THREAD

**Issue by livlab** [thecarebot/carebot#65]
Current Slack account has reached the limit of integrations (not sure what integrations other teams are using, giphy seems to be one of them). 

We REALLY need to be able to add more integrations so that we may a) test our own project b) work efficiently (github integration for issues, testing other bots, etc).

**Comment by livlab** [comment]
Sent Wright a message but suspect he's traveling because I saw him at Union Station this morning :/ If I don't hear back by mid-day will try someone else on his team.

**Comment by livlab** [comment]
Ok, so, they have a bunch of integrations in there that precedes their time so they are going to look through and get rid of any that they don't need. I asked for at least "two slots" so that we can do our own carebot one and add github. We'll hear back by tomorrow. 

If they can't get rid of enough integrations for whatever reason, we'll think of something else. It sounds like the person who initiated the Slack adoption left the company and progress in getting an Enterprise account without limits died off. Not a problem we should worry about so I'll deal with this until we have what we minimally need.

**Comment by livlab** [comment]
Ok, added github to post to carebot-notices. Hello World.

**Comment by livlab** [comment]
Ok, also added travis CI. Need to configure it in Travis later to make it work. will send you instructions.

**Comment by hampelm** [comment]
:fireworks: Thank you!

**Comment by livlab** [comment]
added a third integration just to keep a slot saved for Carebot (apparently more people have wanted this just nobody bothered them enough to make them open up some slots haha)
