### ISSUE TITLE
Consider vulnerability testing

### ISSUE THREAD

**Issue by livlab** [thecarebot/carebot#75]
Been reading about https://snyk.io/ and am interested in testing it. Given the nature of this project, seems like a good place to check.

**Comment by hampelm** [comment]
A similar service I've used is Gemnaisum: http://gemnasium.com/. They're pretty popular in the Ruby world and also support Python (and I believe node?). It sends urgent emails, sometimes multiple times a day, when there are security updates to any of the dependencies: 

<img width="630" alt="screen shot 2016-02-10 at 3 30 37 pm" src="https://cloud.githubusercontent.com/assets/86435/12960810/4551bda2-d00b-11e5-92dc-46be40f14567.png">

It also can do static analysis to detect other potential problems like cross-site scripting vulnerabilities.

**Comment by livlab** [comment]
Neat - this is a new area for me, so I'm interested in taking a look at both.

**Comment by hampelm** [comment]
I've got Gemnaisum running for Carebot to alert us if there are security vulnerabilities in libraries we use: https://gemnasium.com/github.com/thecarebot/carebot
