### ISSUE TITLE
Tracker should autodiscover new stories

### ISSUE THREAD

**Issue by hampelm** [thecarebot/carebot#82]

**Comment by hampelm** [comment]
Good news! We can autodiscover project slugs: 

```
    self.results = self.service.data().ga().get(
        ids='ga:100688391',
        start_date='5daysAgo',
        end_date='today',
        metrics='ga:totalEvents',
        dimensions='ga:eventCategory',
        filters='ga:eventAction==on-screen',
        start_index='1',
        max_results='500').execute()
```

Bad news! We can't autodiscover the story URLs for viz, and we don't get the page URLs. So we'll have to get them from the project spreadsheet after all.

**Comment by hampelm** [comment]
For non-embedded stories, we can probably automatically get the story URL and title.

**Comment by livlab** [comment]
Yay! That's really great news.

**Comment by hampelm** [comment]
Scraper for stories: 
https://github.com/nprapps/graeae/blob/b38cdd3de74fb239fdcc92619e92bcfb0818bda3/fabfile/cron_jobs.py#L73

https://github.com/nprapps/graeae/blob/b38cdd3de74fb239fdcc92619e92bcfb0818bda3/scrapers/spreadsheet/scraper.py
