### ISSUE TITLE
README.md run project instruction

### ISSUE THREAD

**Issue by livlab** [thecarebot/carebot#86]
After running export SLACKBOT_API_TOKEN=foo (replacing foo with the actual API token), I got this:

![image](https://cloud.githubusercontent.com/assets/1936365/13089867/c9abb044-d4c0-11e5-92c5-3eb62e14bfd9.png)

am I doing something wrong or do we need to adjust the instructions?

**Comment by hampelm** [comment]
I added (hopefully) better instructions. Let me know if those work for you! I can also send over the config file. It's probably worthwhile testing from scratch.

**Comment by livlab** [comment]
Not sure I understand this yet. I'll ask during iteration review.

**Comment by hampelm** [comment]
The Google Analytics setup has a lot of steps -- I think there probably are some I didn't note at the time. Happy to do a screenshare before or after iteration review too.

**Comment by hampelm** [comment]
We've done a lot of improvements to the readme as part of the code convening -- closing this for now.
